// generated by stringer -type=TrackerEventType; DO NOT EDIT

package replay

import "fmt"

const (
	_TrackerEventType_name_0 = "EventPlayerStatsEventUnitBornEventUnitDiedEventOwnerChangeEventTypeChangeEventUnknown1"
	_TrackerEventType_name_1 = "EventUnitPositionsEventPlayerSetup"
)

var (
	_TrackerEventType_index_0 = [...]uint8{0, 16, 29, 42, 58, 73, 86}
	_TrackerEventType_index_1 = [...]uint8{0, 18, 34}
)

func (i TrackerEventType) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _TrackerEventType_name_0[_TrackerEventType_index_0[i]:_TrackerEventType_index_0[i+1]]
	case 8 <= i && i <= 9:
		i -= 8
		return _TrackerEventType_name_1[_TrackerEventType_index_1[i]:_TrackerEventType_index_1[i+1]]
	default:
		return fmt.Sprintf("TrackerEventType(%d)", i)
	}
}
